export const ERROR_CODES = {
  NODE_IS_ALREADY_EXECUTED: 'NODE_IS_ALREADY_EXECUTED',
  WORKFLOW_IS_ALREADY_EXECUTED: 'WORKFLOW_IS_ALREADY_EXECUTED',
  NODE_IS_NOT_EXECUTED: 'NODE_IS_NOT_EXECUTED',
  CYCLIC_WORKFLOW_DETECTED: 'CYCLIC_WORKFLOW_DETECTED',
  NODE_METHOD_NOT_IMPLEMENTED: 'NODE_METHOD_NOT_IMPLEMENTED',
  NODE_EXECUTION_FAILED: 'NODE_EXECUTION_FAILED',
}
